
      # command: redis-server --requirepass mypassword <--- this works as expected
      # command: redis-server --requirepass ${REDIS_PASSWORD} <-- while this does not
#      command: redis-server --requirepass $${REDIS_PASSWORD} <-- and this does not work either

#      env_file:
#        - .env.prod
version: '2'

services:
  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/var/lib/redis/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

#  volumes:
#    cache:
#      driver: local